import React, { useRef } from "react";
import "../assets/css/PhotoGrid.css";
import { formatDate } from "../utils/helpers";

const PhotoGrid = ({
  currentUser,
  thumbnails,
  sasToken,
  onPhotoDelete,
  onPhotoLoad,
  onPhotoDownload,
}) => {
  // get an array of thumbnail urls that are generated by waiting for ther result of loadImage
  const newestImage = useRef();

  const loadImage = async (url) => {
    newestImage.current.classList.add("loading");
    let fetchResponse = await fetch(url);
    if (fetchResponse.status === 200) {
      newestImage.current.classList.remove("loading");
      newestImage.current.src = url;
    } else {
      setTimeout(() => loadImage(url), 500);
    }
  };

  console.log("thumbnails", thumbnails);
  console.log(currentUser);
  return (
    <div className="photo-grid">
      {thumbnails.map((thumbnail, index) => (
        <div className="thumbnail-container" key={"thumbnail-" + index}>
          <button
            className="thumbnail-button"
            onClick={(event) => onPhotoLoad(event, thumbnail.serialisedFileName)}>
            <img
              className="thumbnail"
              ref={index === thumbnails.length - 1 ? newestImage : null}
              src={thumbnail.thumbnailUrl + sasToken}
              alt="thumbnail"
              onError={async () => await loadImage(thumbnail.thumbnailUrl + sasToken)}
            />
          </button>
          <div>
            <p className="text-center">
              Uploaded by {thumbnail.owner.username} on {formatDate(thumbnail.uploadDate)}
            </p>
            <div className="button-row">
              <button
                className="btn"
                onClick={(event) => onPhotoDownload(event, thumbnail.fileName)}>
                Download
              </button>
              <button
                className={`btn ${thumbnail.owner._id === currentUser ? "" : "hidden"}`}
                onClick={(event) => onPhotoDelete(event, thumbnail)}>
                Delete
              </button>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
};

export default PhotoGrid;
